import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Hero from '@/components/Hero'
import Layout from '@/components/layout/Layout'
import About from '@/components/About'
import Skills from '@/components/Skills'
import Projects from '@/components/Projects'


export default function Home() {

  return (
    <div>
      <Head>
        <title>Nims| Front-End-Developer </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Navbar />
      <Layout>
        <Hero />
        <About />
        <Skills/>
        <Projects />
      </Layout>
    </div>
  )
}
